name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Stellen Sie sicher, dass requirements.txt vorhanden ist

    - name: Run tests
      run: |
        python your_test_script.py  # Ersetzen Sie "your_test_script.py" durch den Namen Ihres Testskripts
